source "https://rubygems.org"
gem "jekyll", "~> 3.10"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jemoji"
gem "kramdown-parser-gfm"
gem "minimal-mistakes-jekyll"
gem "webrick"
